spring:
  application:
    name: email

  datasource:
    username: root
    password: 147852
    url: jdbc:mysql://localhost:3306/emailbase
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port:8080
